### PR TITLE
tokio-native-tls: remove unused dependencies

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Would be nice to get this change merged if someone with review perms has a free minute. I wasn't able to build tip of master without it and it looks like others are hitting it too (https://github.com/tokio-rs/tls/pull/135).

**Comment by djc** [comment]
@quininer @hawkw @LucioFranco ping? This seems pretty uncontroversial, would like to get this in to pass CI so we can get tokio-rustls out with the new rustls version.

**Review by quininer — APPROVED** [review]
LGTM, but I don't know enough about native-tls .

**Review by robjtede — CHANGES_REQUESTED** [review]
From what I can tell (testing on macOS), this dependency spec doesn't do anything.

Grepping for `security_framework` shows nothing in this repo and `security-framework-sys v2.8.0` + `security-framework v2.8.2` get selected anyway via `native-tls`.

This line dates back to the initial commit, but it's not clear that it served any purpose even then.

My suggestion is to delete this section instead of updating the dep spec.

**Comment by djc** [comment]
@robjtede huh, you're right. I was able to remove a whole bunch of dependencies, let's see what CI thinks.

**Review by robjtede — APPROVED** [review]

**Review by cpu — APPROVED** [review]

**Comment by cpu** [comment]
Thanks for tidying this up everyone.

**Pull request merged**
